pipeline {
  agent any
  stages {
    stage ("Check www.example.com response code") {
      steps{
        withCredentials([string(credentialsId: 'ithome-telegram-bot-token', variable: 'TOKEN')]){
          withCredentials([string(credentialsId: 'ithome-telegram-notification-group', variable: 'GROUP_ID')]){
            script {
              // Assign the response code within a script block
              response_code = sh(
                script: "curl -o /dev/null -s -w %{http_code} www.example.com",
                returnStdout: true
              ).trim().toInteger()
              
              // Check the response code and send a Telegram message if needed
              if (response_code != 201) {
                def message = "www.example.com response code != 201. Got: ${response_code}"
                sh """
                  curl -X GET "https://api.telegram.org/bot${TOKEN}/sendMessage" \
                    -d "chat_id=${GROUP_ID}&text=${message}"
                """
              }
            }
          }
        }
      }
    }
  }
}