// www.example.com
library 'ithome-utils'

webSiteCodePipeline(domain: 'www.example.com', code: 200)
webSiteCodePipeline(domain: 'www.google.com', code: 200)
webSiteCodePipeline(domain: 'test.k6.io', code: 308)
webSiteCodePipeline(domain: 'k6.io', code: 301)